#!/bin/bash

sudo apt update
sudo apt install git make xserver-xorg xinit apt-transport-https curl libx11-dev libxft-dev libxinerama-dev zathura ranger -y

cd
cd .config
mkdir dwm
cd dwm
git clone git://git.suckless.org/dwm
cd dwm
sudo make clean install
cd ..
git clone git://git.suckless.org/st
cd st
sudo make clean install
cd ..
wget https://dl.suckless.org/tools/dmenu-4.9.tar.gz
tar -xvf dmenu-4.9.tar.gz
cd dmenu-4.9
sudo make clean install

cd
touch .xinitrc
echo "dwm" > .xinitrc


curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
sudo apt update
sudo apt install brave-browser -y
