#!/bin/bash

# If you are running this script, it is because you ran git clone https://github.com/cheomanigua/config.git
# and run cd config

sudo apt update
sudo apt install vim xserver-xorg xinit -y
sudo apt install network-manager -y
sudo apt install git make libx11-dev libxft-dev libxinerama-dev -y
sudo apt install apt-transport-https curl -y


### Install and configure dwm

cd
mkdir suckless 
cd suckless
git clone git://git.suckless.org/dwm
cd dwm
cp ../../config/suckless/ubuntu/dwm/* .
sudo make clean install


### Install and configure st

cd ..
git clone git://git.suckless.org/st
cd st
cp ../../config/suckless/ubuntu/st/* .
sudo make clean install


### Install and configure dmenu

cd ..
wget https://dl.suckless.org/tools/dmenu-5.0.tar.gz
tar -xvf dmenu-5.0.tar.gz
cd dmenu-5.0
sudo make clean install


### Install and configure dwm-bar

cd ..
git clone https://github.com/joestandring/dwm-bar.git
cp -r ../config/suckless/ubuntu/dwm-bar/* dwm-bar
cd


### Install several packages

sudo apt install -y feh ranger zathura simplescreenrecorder curl lynx pulseaudio pavucontrol vscode 


### Creating and configuring .xinitrc
mv config/suckless/ubuntu/wallpaper.jpg .
cat <<EOT >> .xinitrc
setxkbmap es
feh --bg-scale wallpaper.jpg &
suckless/dwm-bar/dwm_bar.sh &
exec dwm
EOT


curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
sudo apt update
sudo apt install -y brave-browser

